# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'work2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1126, 901)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Dialog.setPalette(palette)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(470, 0, 241, 81))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(400, 79, 61, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(490, 79, 61, 40))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(240, 79, 71, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(221, 119, 171, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(221, 159, 171, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(221, 199, 171, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(240, 249, 71, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(221, 289, 131, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(221, 329, 161, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(221, 369, 161, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(630, 79, 71, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_7.setGeometry(QtCore.QRect(611, 120, 171, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_8.setGeometry(QtCore.QRect(611, 159, 161, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(880, 79, 61, 40))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(790, 79, 61, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(630, 249, 71, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checkBox_9 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_9.setGeometry(QtCore.QRect(611, 199, 131, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_10.setGeometry(QtCore.QRect(611, 289, 171, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_11.setGeometry(QtCore.QRect(611, 329, 131, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_12.setGeometry(QtCore.QRect(611, 369, 171, 51))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(305, 261, 61, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(696, 91, 61, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(696, 261, 81, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(410, 129, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(410, 170, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(410, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(410, 300, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(410, 340, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(410, 380, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(800, 130, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(800, 340, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(800, 300, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(800, 170, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(800, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(800, 380, 41, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(493, 130, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(493, 170, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(493, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(493, 300, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(493, 340, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(493, 380, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(883, 130, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(883, 170, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setGeometry(QtCore.QRect(883, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_10.setEnabled(False)
        self.lineEdit_10.setGeometry(QtCore.QRect(883, 300, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setGeometry(QtCore.QRect(883, 340, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_12.setEnabled(False)
        self.lineEdit_12.setGeometry(QtCore.QRect(883, 380, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(210, 424, 721, 91))
        self.groupBox.setObjectName("groupBox")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(18, 15, 81, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(138, 15, 91, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(270, 15, 61, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setGeometry(QtCore.QRect(393, 15, 61, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setGeometry(QtCore.QRect(516, 15, 71, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(649, 15, 61, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 50, 641, 21))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(6)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 524, 721, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(23, 15, 81, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(240, 15, 61, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(452, 15, 71, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(667, 15, 31, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(40, 50, 641, 21))
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(4)
        self.horizontalSlider_2.setSingleStep(1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 624, 721, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(29, 27, 91, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(104, 27, 91, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(184, 27, 91, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(210, 704, 721, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_4.setGeometry(QtCore.QRect(29, 27, 91, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_5.setGeometry(QtCore.QRect(104, 27, 91, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_6.setGeometry(QtCore.QRect(184, 27, 91, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(210, 787, 721, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(215, 840, 71, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "C109156144湯群毅"))
        self.label.setText(_translate("Dialog", "熱門飲品推薦"))
        self.label_2.setText(_translate("Dialog", "單價"))
        self.label_3.setText(_translate("Dialog", "數量"))
        self.label_4.setText(_translate("Dialog", "找好茶"))
        self.checkBox.setText(_translate("Dialog", "四季春青茶"))
        self.checkBox_2.setText(_translate("Dialog", "黃金烏龍"))
        self.checkBox_3.setText(_translate("Dialog", "8冰綠"))
        self.label_5.setText(_translate("Dialog", "找拿鐵"))
        self.checkBox_4.setText(_translate("Dialog", "烏龍拿鐵"))
        self.checkBox_5.setText(_translate("Dialog", "珍珠紅茶拿鐵"))
        self.checkBox_6.setText(_translate("Dialog", "布丁紅茶拿鐵"))
        self.label_6.setText(_translate("Dialog", "找奶茶"))
        self.checkBox_7.setText(_translate("Dialog", "燕麥奶茶"))
        self.checkBox_8.setText(_translate("Dialog", "烏龍奶"))
        self.label_7.setText(_translate("Dialog", "數量"))
        self.label_8.setText(_translate("Dialog", "單價"))
        self.label_9.setText(_translate("Dialog", "找新鮮"))
        self.checkBox_9.setText(_translate("Dialog", "珍珠奶茶"))
        self.checkBox_10.setText(_translate("Dialog", "金桔檸檬"))
        self.checkBox_11.setText(_translate("Dialog", "檸檬多多"))
        self.checkBox_12.setText(_translate("Dialog", "8冰茶"))
        self.label_10.setText(_translate("Dialog", "(鮮奶)"))
        self.label_11.setText(_translate("Dialog", "(奶精)"))
        self.label_12.setText(_translate("Dialog", "(無咖啡因)"))
        self.label_13.setText(_translate("Dialog", "$30"))
        self.label_14.setText(_translate("Dialog", "$30"))
        self.label_15.setText(_translate("Dialog", "$50"))
        self.label_16.setText(_translate("Dialog", "$60"))
        self.label_17.setText(_translate("Dialog", "$60"))
        self.label_18.setText(_translate("Dialog", "$70"))
        self.label_19.setText(_translate("Dialog", "$50"))
        self.label_20.setText(_translate("Dialog", "$70"))
        self.label_21.setText(_translate("Dialog", "$60"))
        self.label_22.setText(_translate("Dialog", "$50"))
        self.label_23.setText(_translate("Dialog", "$50"))
        self.label_24.setText(_translate("Dialog", "$50"))
        self.groupBox.setTitle(_translate("Dialog", "甜度"))
        self.label_25.setText(_translate("Dialog", "正常甜(標準)"))
        self.label_26.setText(_translate("Dialog", "不要太甜(9分)"))
        self.label_27.setText(_translate("Dialog", "少糖(7分)"))
        self.label_28.setText(_translate("Dialog", "半糖(5分)"))
        self.label_29.setText(_translate("Dialog", "微糖(1/4分)"))
        self.label_30.setText(_translate("Dialog", "無糖(健康)"))
        self.groupBox_2.setTitle(_translate("Dialog", "冰等"))
        self.label_31.setText(_translate("Dialog", "正常冰"))
        self.label_33.setText(_translate("Dialog", "少冰"))
        self.label_35.setText(_translate("Dialog", "微冰"))
        self.label_36.setText(_translate("Dialog", "去冰"))
        self.groupBox_3.setTitle(_translate("Dialog", "付款方式"))
        self.radioButton.setText(_translate("Dialog", "現金"))
        self.radioButton_2.setText(_translate("Dialog", "linepay"))
        self.radioButton_3.setText(_translate("Dialog", "信用卡"))
        self.groupBox_4.setTitle(_translate("Dialog", "自備飲料杯"))
        self.radioButton_4.setText(_translate("Dialog", "大"))
        self.radioButton_5.setText(_translate("Dialog", "小"))
        self.radioButton_6.setText(_translate("Dialog", "無"))
        self.label_32.setText(_translate("Dialog", "結帳金額"))
        self.pushButton.setText(_translate("Dialog", "結帳"))

        self.checkBox.clicked.connect(self.chk_onClick)
        self.checkBox_2.clicked.connect(self.chk2_onClick)
        self.checkBox_3.clicked.connect(self.chk3_onClick)
        self.checkBox_4.clicked.connect(self.chk4_onClick)
        self.checkBox_5.clicked.connect(self.chk5_onClick)
        self.checkBox_6.clicked.connect(self.chk6_onClick)
        self.checkBox_7.clicked.connect(self.chk7_onClick)
        self.checkBox_8.clicked.connect(self.chk8_onClick)
        self.checkBox_9.clicked.connect(self.chk9_onClick)
        self.checkBox_10.clicked.connect(self.chk10_onClick)
        self.checkBox_11.clicked.connect(self.chk11_onClick)
        self.checkBox_12.clicked.connect(self.chk12_onClick)

        self.radioButton.clicked.connect(self.rdb_onClick)
        self.radioButton_2.clicked.connect(self.rdb2_onClick)
        self.radioButton_3.clicked.connect(self.rdb3_onClick)
        self.radioButton_4.clicked.connect(self.rdb4_onClick)
        self.radioButton_5.clicked.connect(self.rdb5_onClick)
        self.radioButton_6.clicked.connect(self.rdb6_onClick)
        
        self.pushButton.clicked.connect(self.bnt_onClick)
        
    def chk_onClick(self):
        if self.checkBox.isChecked():
            self.lineEdit.setEnabled(True)
        else:
            self.lineEdit.setEnabled(False)
    def chk2_onClick(self):
        if self.checkBox_2.isChecked():
            self.lineEdit_2.setEnabled(True)
        else:
            self.lineEdit_2.setEnabled(False)
    def chk3_onClick(self):
        if self.checkBox_3.isChecked():
            self.lineEdit_3.setEnabled(True)
        else:
            self.lineEdit_3.setEnabled(False)
    def chk4_onClick(self):
        if self.checkBox_4.isChecked():
            self.lineEdit_4.setEnabled(True)
        else:
            self.lineEdit_4.setEnabled(False)
    def chk5_onClick(self):
        if self.checkBox_5.isChecked():
            self.lineEdit_5.setEnabled(True)
        else:
            self.lineEdit_5.setEnabled(False)
    def chk6_onClick(self):
        if self.checkBox_6.isChecked():
            self.lineEdit_6.setEnabled(True)
        else:
            self.lineEdit_6.setEnabled(False)
    def chk7_onClick(self):
        if self.checkBox_7.isChecked():
            self.lineEdit_7.setEnabled(True)
        else:
            self.lineEdit_7.setEnabled(False)
    def chk8_onClick(self):
        if self.checkBox_8.isChecked():
            self.lineEdit_8.setEnabled(True)
        else:
            self.lineEdit_8.setEnabled(False)
    def chk9_onClick(self):
        if self.checkBox_9.isChecked():
            self.lineEdit_9.setEnabled(True)
        else:
            self.lineEdit_9.setEnabled(False)
    def chk10_onClick(self):
        if self.checkBox_10.isChecked():
            self.lineEdit_10.setEnabled(True)
        else:
            self.lineEdit_10.setEnabled(False)
    def chk11_onClick(self):
        if self.checkBox_11.isChecked():
            self.lineEdit_11.setEnabled(True)
        else:
            self.lineEdit_11.setEnabled(False)
    def chk12_onClick(self):
        if self.checkBox_12.isChecked():
            self.lineEdit_12.setEnabled(True)
        else:
            self.lineEdit_12.setEnabled(False)

    def rdb_onClick(self):
        self.radioButton.setChecked(True)
        self.radioButton_2.setChecked(False)
        self.radioButton_3.setChecked(False)
    def rdb2_onClick(self):
        self.radioButton.setChecked(False)
        self.radioButton_2.setChecked(True)
        self.radioButton_3.setChecked(False)
    def rdb3_onClick(self):
        self.radioButton.setChecked(False)
        self.radioButton_2.setChecked(False)
        self.radioButton_3.setChecked(True)
    def rdb4_onClick(self):
        self.radioButton_4.setChecked(True)
        self.radioButton_5.setChecked(False)
        self.radioButton_6.setChecked(False)
    def rdb5_onClick(self):
        self.radioButton_4.setChecked(False)
        self.radioButton_5.setChecked(True)
        self.radioButton_6.setChecked(False)
    def rdb6_onClick(self):
        self.radioButton_4.setChecked(False)
        self.radioButton_5.setChecked(False)
        self.radioButton_6.setChecked(True)
    
    def bnt_onClick(self):
        _translate = QtCore.QCoreApplication.translate
        sweet = {1:'正常甜(標準)',2:'不要太甜(9分)',3:'少糖(7分)',4:'半糖(5分)',5:'微糖(1/4分)',6:'無糖(健康)'}
        temp = self.horizontalSlider.value()
        sweettemp = "甜度 = " + str(sweet[temp])
        ice = {1:'正常冰',2:'少冰',3:'微冰',4:'去冰'}
        temp2 = self.horizontalSlider_2.value()
        icetemp = "冰等 = " + str(ice[temp2])
        
        if self.radioButton.isChecked():
            pay = "付款方式 = 現金"
        elif self.radioButton_2.isChecked():
            pay = "付款方式 = linepay"
        elif self.radioButton_3.isChecked():
            pay = "付款方式 = 信用卡"
            
        total = 0
        num = 0
        if self.checkBox.isChecked():
            num = int(self.lineEdit.text())
            total += 30 * num
        if self.checkBox_2.isChecked():
            num = int(self.lineEdit_2.text())
            total += 30 * num
        if self.checkBox_3.isChecked():
            num = int(self.lineEdit_3.text())
            total += 50 * num
        if self.checkBox_4.isChecked():
            num = int(self.lineEdit_4.text())
            total += 60 * num
        if self.checkBox_5.isChecked():
            num = int(self.lineEdit_5.text())
            total += 60 * num
        if self.checkBox_6.isChecked():
            num = int(self.lineEdit_6.text())
            total += 70 * num
        if self.checkBox_7.isChecked():
            num = int(self.lineEdit_7.text())
            total += 50 * num
        if self.checkBox_8.isChecked():
            num = int(self.lineEdit_8.text())
            total += 50 * num
        if self.checkBox_9.isChecked():
            num = int(self.lineEdit_9.text())
            total += 50 * num
        if self.checkBox_10.isChecked():
            num = int(self.lineEdit_10.text())
            total += 60 * num
        if self.checkBox_11.isChecked():
            num = int(self.lineEdit_11.text())
            total += 70 * num
        if self.checkBox_12.isChecked():
            num = int(self.lineEdit_12.text())
            total += 50 * num
            
        if self.radioButton_4.isChecked():
            total -= 2
        elif self.radioButton_5.isChecked():
            total -= 1
        elif self.radioButton_6.isChecked():
            total -= 0

        output_text = pay + '，' + sweettemp + '，' + icetemp + '，共' + str(round(total,2)) + '元'
        self.label_32.setText(_translate("Dialog", output_text))
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

